plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.riodosul.niveldorio'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.riodosul.niveldorio'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '0.6.0-test'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
